version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: jobs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  migration:
    image: migrate/migrate:v4.16.2
    container_name: migration_runner
    volumes:
      - ./database/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://user:12345678@db:5432/jobs_db?sslmode=disable", "up"]
    depends_on:
      - db

volumes:
  postgres_data: